### PR TITLE
ToCode Solution: תרגיל מסכם מחלקות

### PR DESCRIPTION
**Pull request by User1978**

### CODE REVIEW

**Comment by User1978** [comment]
Hi,

I haven't finished writing the game. I'm a bit lost and I want to know if I'm on the right direction. 

More specifically, I'm trying to see in each round if we have a winner. I wrote Game.winner function for that but I don't know how exactly to call it. Could you please provide some help?
Thanks,

**Comment by szabgab** [comment]
instead of `if Game.winner == True:` have you tried `if currentgame.winner():` ?

**Comment by User1978** [comment]
I tried. I got: 
TypeError: winner() takes no arguments (1 given)

**Comment by szabgab** [comment]
Right. Instead of `def winner():` you need to declare it as `def winner(self):` accepting the instance object as well.

**Comment by User1978** [comment]
I tried that. I got:
if currentgame.winner() == True:
TypeError: 'bool' object is not callable

How do I set the def winner(self) function to be True / False ? 
Can I do something like: if x: self.winner = True ? can I than return it? 

Why when I do:    if currentgame.winner(self):
I get NameError: name 'self' is not defined ? My function starts with self.winner = False should I do something like self.winner = winner ?

**Comment by szabgab** [comment]
You don't need to compare it to True, just write
```
if currentgame.winner():
```
but I am not sure if this is the problem. Upload your current version of the code and tell me how do you run it so I can check it.

**Comment by User1978** [comment]
I run main.py
It will ask you for row, than column
and will try to see if you won

**Comment by szabgab** [comment]
You have
```
    def winner(self):
        self.winner = False
```
basically the first statement in that function redefines the name winner from being a method to being a boolean attribute. That's why the second time you try to call the winner() method it complains that it is a boolean.

You should rename either the attribute or the method.

**Comment by User1978** [comment]
I'm missing something here. I want the def winner(self) function to return True if you won and false if you didn't. I need it to be False when I start a new game and True if I meet a condition. 
If I change the attribute to self.win = False or win=False my statement is always True. All if conditions are met and I win the game again and again for each move.

**Comment by szabgab** [comment]
Actually I am not even sure you need an attribute called 'win' or 'winner'. What you need is a method
that calculates if there is a winner and who is the winner. Which is I think done by the current 'winner' method.

"winner" - of the boards, from the name, does not sound like a function that should return boolean. It should probably return the name or the object of the play that is the winner. (Now as I can see, it is printing it). I would think that if the method is called at a time when there is no winner, then it might return `None`.

**Comment by User1978** [comment]
Hi,
The game works great :)
I fail some unit tests, apparently because I did not use the same names, BUT all the required functionality is there.

**Comment by szabgab** [comment]
Congratulations!

The UI could be a bit more visual, printing a 3x3 board instead of the list-of-lists, but well.

**Comment by User1978** [comment]
This is my first program, in any language. I'm just happy it works :)
But, I fixed it a bit.

**Comment by szabgab** [comment]
Even better!
Here is a 🍰

**Comment by szabgab** [comment]
Now starts the real fun as you start having ideas of what to program and start implementing them and improving them.

**Pull request closed without merging**
