### PR TITLE
ToCode Solution: תרגול פונקציות

### PR DESCRIPTION
**Pull request by User1978**

### CODE REVIEW

**Comment by User1978** [comment]
Hi,
1-4 seems to work as required. I don't understand why my unit tests are failing. 
Regarding no. 5, i don't know how to approach this. I would appreciate some help.
Thanks

**Comment by szabgab** [comment]
04 also fails.
05 you started well, but instead of collecting the values in a list (called listed) the grouped, needs to have a key for each key and the values need to be the lists. So grouped will hold several lists, one for each key.

**Comment by szabgab** [comment]
Oh I think I misunderstood you. You were asking why the Unit tests of 4 are failing. 
```
AssertionError: ['fantastic', 'python'] != '\nfantastic\npython'
```
It seems you return a string of the filtered values while the test is expecting a list of those values.

**Comment by szabgab** [comment]
As we are getting close to the finish line in this course I'd like to make sure there are no open questions left. If something is unclear with this or another exercise, do ask about the part that is unclear. I'll explain it in more detail.

**Comment by szabgab** [comment]
now they are good. 👍

**Pull request closed without merging**
