### PR TITLE
ToCode Solution: תרגול פונקציות

### PR DESCRIPTION
**Pull request by shlomiiss**

### CODE REVIEW

**Comment by szabgab** [comment]
Oh, please the indentation. Use 4 spaces to make it readable and standard.
02: you don't need all those flags. You could just write this in a single conditional expression.
04: In python we usually don't need and want to iterate over the indexes. Instead of that we directly iterate over the values. Try this:

```
for word in words:
```
05: missing.

**Comment by szabgab** [comment]
As we are getting close to the finish line in this course I'd like to make sure there are no open questions left. If something is unclear with this or another exercise, do ask about the part that is unclear. I'll explain it in more detail.

**Comment by szabgab** [comment]
Exercise 01 is still failing. Could you check why? Is the indentation correct?
others are good! 👍

**Comment by shlomiiss** [comment]
I recheck it and In excerice 01 indentation is fine. What next ?

On Sun, Dec 18, 2016, 17:45 Gabor Szabo <notifications@github.com> wrote:

Exercise 01 is still failing. Could you check why? Is the indentation
correct?
others are good! 👍

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tocodeil/python-course-examples/pull/98#issuecomment-267828418>,
or mute the thread

**Comment by shlomiiss** [comment]
Sorry mistake.  I have indeed indentation issues. Fixing and will upload

**Comment by szabgab** [comment]
That's not what I meant.
There is a logical error caused by indentation. That's what causing the tests to fail.
Even if you run `python 01.py` you don't get the results you are expecting.

**Comment by shlomiiss** [comment]
I'm checking it with spec.py

**Comment by szabgab** [comment]
ok, let's  move on.

**Pull request closed without merging**
