### PR TITLE
ToCode Solution: תרגול רשימות

### PR DESCRIPTION
**Pull request by User1978**

### CODE REVIEW

**Comment by User1978** [comment]
I see that exercise is still open.
1. I guess it is because I did not use list comprehension properly?
2. Can I see all things that are still open and require my attention in Github ?

**Comment by szabgab** [comment]
Hmm, I went over all the open submissions twice, I am not sure how I missed this. Sorry for that.
the comment I'd make is that it would be probably better to write `ord('a')` instead of 65 and `ord('z')+1` instead of 123.

I'd normally close this even though the solution was not list comprehension.
Let me know if you'd like to resubmit this or if I should close it.

This is the list of all the open Pull-requests submitted by you:
https://github.com/tocodeil/python-course-examples/pulls/User1978

**Comment by User1978** [comment]
Hi,

I thought that I need to use 65 and 123 and not 'ord' because of the hint:
"look for the chr function"

I'd appreciate it if you could close this, since I'm trying to finish the
tic-tac-toe game in time.

Thanks

**Comment by szabgab** [comment]
Sure.

**Pull request closed without merging**
