### PR TITLE
ToCode Solution: תרגול פונקציות

### PR DESCRIPTION
**Pull request by ItayElbaz**

### CODE REVIEW

**Comment by szabgab** [comment]
Please check why do the tests fail and submit the fixed version.

**Comment by ItayElbaz** [comment]
in 02 we've been asked to make an exceptions.. for some reason those exceptions seems as fail to the spec.py.
05 - i don't understand why it fails the test

**Comment by szabgab** [comment]
I think you raise the exception in the wrong case.

**Comment by ItayElbaz** [comment]
still..same

**Comment by szabgab** [comment]
You either need to compare `type(x).__name__` with the name of the type or us the `isinstance` function.

**Pull request closed without merging**
