### PR TITLE
ToCode Solution: תרגול מבני נתונים

### PR DESCRIPTION
**Pull request by anatshapira**

### CODE REVIEW

**Comment by szabgab** [comment]
1: in this exercise you were supposed to ask the user for userame pw and read it from the keyboard. The actual checking of the values is good.

**Comment by szabgab** [comment]
👍

**Comment by anatshapira** [comment]
Hi Gabor,
Until when can I submit the exercises ?

Anat

**Comment by szabgab** [comment]
Today is the last day.

**Comment by anatshapira** [comment]
:(
so i got till 00:00 ???

**Comment by szabgab** [comment]
go for it 😄

**Comment by anatshapira** [comment]
🤓 I'll leave it , and use the specs for testing...
10X !

**Comment by anatshapira** [comment]
Hi ,
still have 50 min to deadline 😉
I sent you ex 4, I feel i made it to complicated ...
maybe you can just send me the correct answer and i'll understand.

thanks and good night

**Comment by szabgab** [comment]
Instead of
```
    for letter in word:
        letters.append(letter)
    for s in sorted(letters):
        key = key + s
```

you could write

```
key = ''.join(sorted(word))
```

and then you can also remove
```
    key = ""
    letters = []
```

In addition, instead of saving the words as a string in `word_Dic[key]` I'd suggest keeping them as a list:
```
    if not key in word_Dic:
        word_Dic[key] =  []
    word_Dic[key].append(word)
```

**Comment by szabgab** [comment]
You still have 17 minutes 😸

**Comment by szabgab** [comment]
In any case the concept of your solution was good. These are just improvements.

**Comment by anatshapira** [comment]
Many thanks ! :)
I was missing the join part , it saves a lot of coding.
Now I'm going to use all the minutes i got left , to sleep 😛
Good night

בתאריך 22 בדצמ' 2016 23:44,‏ "Gabor Szabo" <notifications@github.com> כתב:

In any case the concept of your solution was good. These are just
improvements.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tocodeil/python-course-examples/pull/130#issuecomment-268897240>,
or mute the thread

**Pull request closed without merging**
