### PR TITLE
ToCode Solution: תרגול קבצים

### PR DESCRIPTION
**Pull request by Balinbal**

### CODE REVIEW

**Comment by Balinbal** [comment]
@szabgab hi, in exercise 02 , it is looks like there is a problem with the test or the file that you try to test.
you got some unnecessary enter between the files, i tried to do some changes in my code with no success( i realy don't know what is the problem) so i upload the origin one that works for me.
can you check it? 
thanks, 
Inbal

**Comment by szabgab** [comment]
I see the test for the first file fails because there is an extra empty line added after the first file.
That's the unnecessary `fout.write('\n')` line

The second file passes its tests.

Otherwise they look good.

**Comment by Balinbal** [comment]
@szabgab hi, where do you see this line in my code?

**Comment by szabgab** [comment]
Line 14 of https://github.com/Balinbal/python-course-examples/blob/7e6b2bb8b10016cb237c3f02f6fde057650e9120/08_files_lab/01.py

**Comment by Balinbal** [comment]
but i was talking about 02.py- in this exercise i had the problem

**Pull request closed without merging**
