### PR TITLE
ToCode Solution: תרגול קבצים

### PR DESCRIPTION
**Pull request by User1978**

### CODE REVIEW

**Comment by User1978** [comment]
Hi,

I had some problems with the second script. Would appreciate some help.

Thanks

**Comment by szabgab** [comment]
It seems in the result the missing values (where one file is shorter than the other) are printed as 'None' instead of being the empty string. Try to fill them with the empty string. See the docs: https://docs.python.org/2/library/itertools.html#itertools.izip_longest

**Comment by User1978** [comment]
Thanks :) 
After watching all of this weeks videos, it is more clear how to read a function in Python

**Comment by szabgab** [comment]
nice 🍪

**Pull request closed without merging**
