### PR TITLE
ToCode Solution: תרגול תחביר

### PR DESCRIPTION
**Pull request by ohady75**
Thanks.
I still failed in running pip install mock so I can use the spec.py
any idea?

### CODE REVIEW

**Comment by szabgab** [comment]
Hi Ohad, 
I am glad you managed to submit the first exercises.

Some of the automatic tests have failed. Please make sure those pass before we continue.

Please note the "All checks have failed" and the link to "Details" under it. That leads to results of the system that checks your submission automatically against the spec. This indicates there were some exercises that failed.

You can run the spec on your computer by cd into the directory where your Python files are e.g.
`cd \Users\foobar\PycharmProhects\untitled` and then run the tests:

```python spec.py```

and you can run it for the individual files using

```
python spec.py TestEx1
python spec.py TestEx2
...
```

The following video provides more detailed explanation how to run the tests
https://www.tocode.co.il/bundles/python/lessons/syntax-lab

**Comment by szabgab** [comment]
Hi Ohad, are the tests passing on you computer?

**Comment by ohady75** [comment]
Yes.


[cid:image001.png@01D2516A.E6F1B870]

**Comment by szabgab** [comment]
1) Please implement and submit all the exercises in this chapter
2) Please install the 'mock' package using pip. If 'pip install mock' says it cannot find pip, then look for 'pip.exe' in yout python installation and run it using full path. As I saw it on someones computer it would be `c:\Python27\scripts\pip.exe install mock` then, in the directory where the solutions and the spec.py file are run `python spec.py TestEx1` to check the first exercise.

**Pull request closed without merging**
