### PR TITLE
ToCode Solution: תרגול תחביר

### PR DESCRIPTION
**Pull request by User1978**

### CODE REVIEW

**Comment by szabgab** [comment]
hi, welcome to the exercise!

The automatic test have failed. Please make sure those pass.

Some of the automatic tests have failed. Please make sure those pass before we continue.

Please note the "All checks have failed" and the link to "Details" under it. That leads to results of the system that checks your submission automatically against the spec. This indicates there were some exercises that failed.

You can run the spec on your computer by cd into the directory where your Python files are e.g.
`cd \Users\itelbaz\PycharmProhects\untitled` and then run the tests:

```python spec.py```

and you can run it for the individual files using

```
python spec.py TestEx1
python spec.py TestEx2
...
```

The following video provides more detailed explanation how to run the tests
https://www.tocode.co.il/bundles/python/lessons/syntax-lab

**Comment by szabgab** [comment]
Thanks for fixing the code so they pass the tests now.
A few notes now:

02: `range(7)` is the same as `range(0,7)`, better to write the former.
In Python 2 we don't put parentheses after the `print` statement.

03: you don't need to create the `number_count` list, you could have calculate the `total_digits` in the same loop as you iterate over the characters of the `random_number` and convert them to `int` for the addition

```
random_number = randint(1, 10000)
total_digits = 0
for c in str(random_number):
    total_digits += int(c)
```

shorter and cleaner.

04: I think the solution with the list is much better here. Congratulations!

05: you don't really need the `else` part here

06: It works but it is quite slow going over all the numbers. There are better algorithms, but you could also just check the multipliers of first_number, instead of every number.

07: nice extra touch of limiting the guesses, but what happens if the user guesses the number in less than 5 ?

**Comment by User1978** [comment]
Thanks for the comments.
I'm uploading a better version of the scripts.
Regarding the second script (02) - I see in my code that I used range(0, 7). I don't know why you don't see it

**Comment by szabgab** [comment]
Maybe my wording was not clear. I saw you used `range(0, 7)` but you could have used `range(7)` as well.

In any case all is good.

**Pull request closed without merging**
