### PR TITLE
ToCode Solution: תרגול תחביר

### PR DESCRIPTION
**Pull request by shlomiiss**

### CODE REVIEW

**Comment by szabgab** [comment]
hi and welcome to the exercise!

Some of the automatic tests have failed. Please make sure those pass before we continue.

Please note the "All checks have failed" and the link to "Details" under it. That leads to results of the system that checks your submission automatically against the spec. This indicates there were some exercises that failed.

You can run the spec on your computer by cd into the directory where your Python files are e.g.
`cd \Users\itelbaz\PycharmProhects\untitled` and then run the tests:

```python spec.py```

and you can run it for the individual files using

```
python spec.py TestEx1
python spec.py TestEx2
...
```

The following video provides more detailed explanation how to run the tests
https://www.tocode.co.il/bundles/python/lessons/syntax-lab

**Comment by szabgab** [comment]
A few comments:

It would be better if you kept the original comment in the files intact.

02: Using the name 'random' for a variable can get confused with the package called random.
That's a sore point of Python. Please don't do that. Use some different name for your variable.

It is recommended to have all your import statement at the top of the file, not after variable declarations.

03: There is no need to pre-declare variables to some arbitrary number (e.g. x =0 and i = 10  have no meaning in this code. They are just confusing the reader)
Also why was the "divider" set to 1000 ? That's unclear to me.

Finally, instead of all these calculations, it is probably much easier to iterate over the digits that make up the number:
```
for c in str(randomnumber):
    # do something here
```

04: Why do you use `\r` there?

05: It is clearer to just write
```
while True:
```
without using a variable `Flag` just for this purpose

06: The idea was that you'd implement gcd, but I guess using an available function is even better!

**Comment by shlomiiss** [comment]
Hello Gabor,
Sorry for the delay I have heavy workload @ my workplace :)
First l'm not a programmer on my daily work.  
1) Indeed. I missed the episode about using the files placed on Githib for the exercises. 
02: clear
03: I need to re-check why.
04: \r is sort of delimiter so the s.replace method will use to replace it with \n (linefeed) in print 
05: clear
06: clear.
BR
Shlomi

**Comment by szabgab** [comment]
Hi Shlomi,

that's why we are here to help you improve.
  Gabor

**Pull request closed without merging**
