### PR TITLE
ToCode Solution: תרגול חריגים

### PR DESCRIPTION
**Pull request by Chagit171**

### CODE REVIEW

**Comment by Chagit171** [comment]
Hi 
I see that Ex2 and Ex3 code is already written(solved) in the example folder.
Am I missing something?

**Comment by szabgab** [comment]
nope, that's a mistake on our end.

**Comment by szabgab** [comment]
1 is 👍

**Comment by Chagit171** [comment]
Thanks.
Untill when I can submmit the last excersize?
בתאריך 22 בדצמ' 2016 18:56, "Gabor Szabo" <notifications@github.com> כתב:

**Comment by szabgab** [comment]
24:00

**Comment by Chagit171** [comment]
And after it you will not review it, right?
בתאריך 22 בדצמ' 2016 19:23, "Gabor Szabo" <notifications@github.com> כתב:

**Comment by szabgab** [comment]
Right.

**Pull request closed without merging**
