### PR TITLE
ToCode Solution: תרגול תחביר

### PR DESCRIPTION
**Pull request by LiatKotigaro**

### CODE REVIEW

**Comment by szabgab** [comment]
Welcome to the exercises!

Please submit all the exercises in this series so we can see if they all pass their tests.

**Comment by LiatKotigaro** [comment]
I’ll submit all the exercises by the end of today.

Thanks,

Liat Kotigaro
R&D BE Core Server Engineer
Communication and Cyber Intelligence (CI)
Verint System Ltd.
Phone: (+972)- 9-9624960
E-mail: liat.kotigaro@verint.com<mailto:liat.kotigaro@verint.com>
Web: <www.verint.com<http://www.verint.com/>>

**Comment by szabgab** [comment]
Thanks for fixing the tests. A few notes:
03: The `str()` function can convert a number to a string. It is clearer than using `%`.
Instead of iterating over the indexes, try iterating over the characters themselves.

04: Keeping the lines in a list and then going over it in reverse order might be a nicer solution,
but once you already kept the lines as a string, there is no need to split them up.

**Comment by LiatKotigaro** [comment]
I updated the code according to your remarks.

Thanks,

Liat Kotigaro
R&D BE Core Server Engineer
Communication and Cyber Intelligence (CI)
Verint System Ltd.
Phone: (+972)- 9-9624960
E-mail: liat.kotigaro@verint.com<mailto:liat.kotigaro@verint.com>
Web: <www.verint.com<http://www.verint.com/>>

**Comment by szabgab** [comment]
Nice!

Go on to the next set of exercises!

**Comment by LiatKotigaro** [comment]
Hi,

I would like to upload the reg-expressions exercise, but it’s already closed. Can I still submit them till Thursday?

Thanks,

Liat Kotigaro
R&D BE Core Server Engineer
Communication and Cyber Intelligence (CI)
Verint System Ltd.
Phone: (+972)- 9-9624960
E-mail: liat.kotigaro@verint.com<mailto:liat.kotigaro@verint.com>
Web: <www.verint.com<http://www.verint.com/>>

**Pull request closed without merging**
