### PR TITLE
ToCode Solution: תרגול תחביר

### PR DESCRIPTION
**Pull request by ItayElbaz**

### CODE REVIEW

**Comment by szabgab** [comment]
Thanks for your first submission!

Please not the "All checks have failed" and the link to "Details" under it. That leads to results of the system that checks your submission automatically against the spec. This indicates there were two exercises that failed.

You can run the spec on your computer by typing in

```python spec.py```

and you can run it for the individual files using

```python spec.py TestEx1```
```python spec.py TestEx2```
...

**Comment by ItayElbaz** [comment]
I've run all the files and they all passed the tested..
Can you explain me why they fail in your tests ?

**Comment by szabgab** [comment]
I don't know what could cause the same test to pass on your computer and fail on both the Travis-CI server and my machine. Could you please verify that the version you have on your computer that passed all the tests is the same that you have submitted?

**Comment by ItayElbaz** [comment]
I've tested them manually..

**Comment by szabgab** [comment]
That's strange. Could you upload a screenshot of your command line with the command you ran and the output you saw?

**Comment by ItayElbaz** [comment]
Sure,
here are 03 04 05 for examples

04py
03py
05py

**Comment by szabgab** [comment]
Thanks. In these cases you are running your own code and visually checking if it returns what you expect. That's important but we also have automated tests that will check if your code returns what we expect. In order to run those tests you need to `cd` into the directory where your Python files are `cd \Users\itelbaz\PycharmProhects\untitled` and then run the tests:
```
python spec.py TestEx1
```
Then please past the results here or if you encounter any problems.

BTW You can watch this video: https://www.tocode.co.il/bundles/python/lessons/syntax-lab it explains how to do this.

**Comment by ItayElbaz** [comment]
specpy

Ok.. tried the spec and got 2 failures - in 01 & 03..
still don't understand why the rest failed in your tests.. 

Thank you for your time,
Itay

**Comment by szabgab** [comment]
OK, then fix those two, and upload them again. Do the same with other series of tests (06_modules_lab) that also had some failures. Let's see if once everything passes on your computer how do the tests behave on the central test server.

**Comment by ItayElbaz** [comment]
Fixed both

**Comment by szabgab** [comment]
Nice. All tests are passing now. I'll check the coding later today.

**Comment by szabgab** [comment]
* Please keep the original comments in the files.
* In 03 Instead of iterating over the indexes in
```
for i in range(len(rand_num)):
    sum_num = sum_num + int(rand_num[i])
```
it is much cleaner to iterate over the actual characters:
```
for c in rand_num:
    sum_num = sum_num + int(c)
```

04: Could you change the code here to avoid the duplicate call to `raw_input` ?
Also I don't think the use of 'else' is really proper here. You'd want that code to execute no matter what.

05. Similar to 04, could you eliminate the duplicate call to randint ?

06: You don't have to go over *every* number. You could go over the multipliers of num_a saving a lot of time.

07: here too it would be better to avoid the duplicate call to raw_input.

**Comment by szabgab** [comment]
nice improvements!

06: Instead of building up a list of values and then taking the first element I'd use `break` to leave the loop at the first hit which is the smallest number anyway.

**Pull request closed without merging**
