### PR TITLE
ToCode Solution: תרגול תחביר

### PR DESCRIPTION
**Pull request by Balinbal**

### CODE REVIEW

**Comment by szabgab** [comment]
Welcome to the exercises!

Some of the automatic tests have failed. Please make sure those pass before we continue.

Please note the "All checks have failed" and the link to "Details" under it. That leads to results of the system that checks your submission automatically against the spec. This indicates there were some exercises that failed.

You can run the spec on your computer by cd into the directory where your Python files are e.g.
`cd \Users\itelbaz\PycharmProhects\untitled` and then run the tests:

```python spec.py```

and you can run it for the individual files using

```
python spec.py TestEx1
python spec.py TestEx2
...
```

The following video provides more detailed explanation how to run the tests
https://www.tocode.co.il/bundles/python/lessons/syntax-lab

**Comment by Balinbal** [comment]
@szabgab Hi, it would be helpful if you could specify mocked functions (so we know that it's the ones we should use), because i've used rangerange instead of randint and it caused several failures. 
Thanks :)

**Comment by szabgab** [comment]
We found out there were some issues with the tests. Those have been fixed now. (At least some of them) Please submit one of your files again to trigger a new run of the tests.

**Comment by szabgab** [comment]
Sorry for that. There were some issues with the tests. They have been fixed since then.
A few comments on your code:

Please leave spaces around  operators to make the code more readable. e.g.
`num = random.randint(1,100)`
instead of
`num=random.randint(1,100)`

and
`digit = num % 10`
instead of
`digit=num%10`

04: nice, though instead of
`user_input_text = [text] + user_input_text`
it is better to write
`user_input_text.insert(0, text)`

06: Iterating over the number 1 by 1 is slow. You could also ave iterated by num1 or num2.

07: Nice. Can you eliminate the duplicate calls to these ?
```
print "Please enter your guess:"
UserNum=int(raw_input())
```

**Comment by Balinbal** [comment]
@szabgab hi, thanks for your comments, i fixed the code.
i want to understand, i need to fix my code for every comments? or just take the comments to myself to improve? because you didn't closed it.

**Comment by szabgab** [comment]
If the changes are small I usually close the PR indicating that you don't need to fix, but when I leave it open it usually indicates I'd like to see some updates. (Or I just forgot to close 😄 )

In the end it is up to you if you'd like to improve that code and maybe get further feedback.

Thanks for the new versions.

Comments:
02: There is also a built-in function called sum(), so it would be probably better to us a different variable name.

03: it is usually better to put all the import statements at the top of the file.
A better solution might be to iterate over the characters instead of doing the arithmetic:
`for c in str(num):`

Thank you

**Pull request closed without merging**
