### PR TITLE
ToCode Solution: תרגול קבצים

### PR DESCRIPTION
**Pull request by anatshapira**

### CODE REVIEW

**Comment by szabgab** [comment]
01 is ok.
02 works but you could have solved this without creating line1 and line2 outside of the 'while' loop. That would create a more readable solution. Would you like to give it a try or shall I close this exercise?

**Comment by anatshapira** [comment]
Giving it a try !

**Comment by anatshapira** [comment]
Is that what you meant ?

**Comment by szabgab** [comment]
almost. You don't even need the two lines at the top
```
line1 = " "
line2 = " "
```
though that would require further changes to the loop inside.

**Comment by anatshapira** [comment]
like this ?

"""
ex02.py
merge 2 files into a third file

"""

import sys

continue_reading = 1
(_, file1, file2, file3) = sys.argv


with open(file1,'r') as f1:
    with open(file2,'r') as f2:
        with open(file3,'w') as f3:
             while continue_reading == 1:
                line1 = f1.readline()
                line2 = f2.readline()
                f3.write(line1)
                f3.write(line2)
                if line1 == "" and line2 == "":
                    continue_reading = 0

**Comment by szabgab** [comment]
yes, except that you don't need another variable 'continue_reading'.
Instead you can have an infinite loop `while True`
and then call `break` when when you are done with the loop.

**Comment by anatshapira** [comment]
👍

**Pull request closed without merging**
