### PR TITLE
ToCode Solution: תרגול תחביר

### PR DESCRIPTION
**Pull request by nomzg**

### CODE REVIEW

**Comment by szabgab** [comment]
Welcome to the exercises.

Some of the automatic tests have failed. Please make sure those pass before we continue.

Please note the "All checks have failed" and the link to "Details" under it. That leads to results of the system that checks your submission automatically against the spec. This indicates there were some exercises that failed.

You can run the spec on your computer by cd into the directory where your Python files are e.g.
`cd \Users\foobar\PycharmProhects\untitled` and then run the tests:

```python spec.py```

and you can run it for the individual files using

```
python spec.py TestEx1
python spec.py TestEx2
...
```

The following video provides more detailed explanation how to run the tests
https://www.tocode.co.il/bundles/python/lessons/syntax-lab

**Comment by nomzg** [comment]
Hey, when I run the script locally, all tests pass besides exercise 6 which I haven't committed. Why don't the others pass?

**Comment by szabgab** [comment]
You are right. The central testing system fails because ex 6 is missing.

**Comment by szabgab** [comment]
02: Please select a different variable name as 'sum' is a built-in function of Python.
It is much better to iterate over numbers created by a range that to count yourself
```
for counter in range(7):
```
05: it would be better not to assign an arbitrary number to 'num' outside of the loop.

**Comment by szabgab** [comment]
As we are getting close to the finish line in this course I'd like to make sure there are no open questions left. If something is unclear with this or another exercise, do ask about the part that is unclear. I'll explain it in more detail.

**Pull request closed without merging**
