### PR TITLE
ToCode Solution: תרגול תחביר

### PR DESCRIPTION
**Pull request by igalzzz**

### CODE REVIEW

**Comment by szabgab** [comment]
Welcome to the exercises.

A few comments:
02: There is a built-in function called `sum` so it  might be better to use a different variable name.
03: Instead of the arithmetic, it might be nicer to iterate over the characters:
`for c in str(number):`

05: the external `number = 0` is not necessary.

06: Iterating over the numbers 1 by 1 is  a bit slow. You could iterate by the multipliers of randA or randB

Otherwise nice solutions!

**Comment by igalzzz** [comment]
Hello Gabor,
Thanks!
Do want me to recommit?

**Comment by szabgab** [comment]
yes, please.

**Comment by szabgab** [comment]
Thank you.

Extra point for using `sys.maxint`!

**Pull request closed without merging**
